const SpectrumCards: [string, string][] = [
  ["Mauvais acteur", "Bon acteur"],
  ["Basique", "Hipster"],
  ["Inutile", "Vaut le coup"],
  ["Inné", "Acqui"],
  ["Arrive lentement", "Arrive soudainement"],
  ["Boulot", "Carrière"],
  ["Arrondi", "Pointu"],
  ["Preuve que Dieu existe", "Preuve que Dieu n'existe pas"],
  ["Aimé", "Détesté"],
  ["Le côté clair de la Force", "Le côté obscure de la Force"],
  ["Stupide", "Brillant"],
  ["Artisanal", "Industriel"],
  ["Personne ne le fait", "Tout le monde le fait"],
  ["Vie brève", "Longue vie"],
  ["Métier dangereux", "Métier sans risque"],
  ["Univers fantastique", "Science-fiction"],
  ["Terre-à-terre", "Fantaisiste"],
  ["A mauvaise réputation", "A bonne réputation"],
  ["Éthique à manger", "Pas éthique à manger"],
  ["Cinéma", "Film"],
  ["Passé de mode", "Tendance"],
  ["Défenseur de la liberté", "Terroriste"],
  ["Superpouvoir pourri", "Superpouvoir génial"],
  ["Inefficace", "Efficace"],
  ["Meilleur chaud", "Meilleur froid"],
  ["Carré", "Rond"],
  ["Temporaire", "Permanent"],
  ["Ressemble à une personne", "Ne ressemble pas à une personne"],
  ["Pourri", "Génial"],
  ["Pire personne vivante", "Meilleur personne vivante"],
  ["Sous-estimé", "Sur-estimé"],
  ["Grignotage", "Alimentation saine"],
  ["Impardonnable", "Pardonnable"],
  ["Échec", "Chef d'œuvre"],
  ["Inoffensif", "Nocif"],
  ["Gryffondor", "Serpentard"],
  ["Insalubre", "Hygiénique"],
  ["Mauvaise musique", "Bonne musique"],
  ["Inutile", "Utile"],
  ["Film qui serait ruiné avec Godzilla", "Film qui serait mieux avec Godzilla"],
  ["Pas important", "Important"],
  ["Facile à épeler", "Difficile à épeler"],
  ["Vicieux", "Vertueux"],
  ["Musicien médiocre", "Musicien de qualité"],
  ["Activité impopulaire", "Activité populaire"],
  ["Divisé", "Entier"],
  ["Peu fiable", "Digne de confiance"],
  ["Facile à tuer", "Difficile à tuer"],
  ["Instable", "Stable"],
  ["Animal en courbe", "Animal anguleux"],
  ["Mauvaise émission télé", "Bonne émission télé"],
  ["Typiquement masculin", "Typiquement féminin"],
  ["Partie du corps inutile", "Partie du corps utile"],
  ["Mode", "Classique"],
  ["Faible", "Fort"],
  ["Céréale dégueulasse", "Céréale délicieuse"],
  ["Mauvais", "Bon"],
  ["Moyennement addictif", "Hautement addictif"],
  ["Inutile en cas d'urgence", "Utile en cas d'urgence"],
  ["Pour enfant", "Pour adulte"],
  ["Villain", "Héros"],
  ["Chose à faire médiocre", "Chose à faire de qualité"],
  ["Ennuyeux", "Passionnant"],
  ["Sent mauvais", "Sent bon"],
  ["Impopulaire", "Populaire"],
  ["Ami", "Ennemi"],
  ["Invention inutile", "Invention utile"],
  ["Libéral", "Conservateur"],
  ["Chaud", "Froid"],
  ["Normal", "Étrange"],
  ["Peu coloré", "Coloré"],
  ["Faible en calorie", "Riche en calorie"],
  ["Sujet facile", "Sujet difficile"],
  ["Inconnu", "Célèbre"],
  ["Rare", "Courant"],
  ["Emoji moche", "Emoji jolie"],
  ["Pas chère", "Chère"],
  ["Arme médiocre", "Arme de qualité"],
  ["Inquiétant", "Rassurant"],
  ["Non essentiel", "Essentiel"],
  ["Sale", "Propre"],
  ["Requiert de la chance", "Requiert des compétences"],
  ["Fade", "Goûtu"],
  ["Sujet barbant", "Sujet fascinant"],
  ["Comme ça vient", "En bonne et due forme"],
  ["Aubaine", "Hors de prix"],
  ["Sec", "Humide"],
  ["Compétence médiocre", "Compétence de qualité"],
  ["Interdit", "Encouragé"],
  ["Chanson triste", "Chanson joyeuse"],
  ["Fragile", "Durable"],
  ["Geek", "Blaireau"],
  ["Bien", "Mal"],
  ["Pire jour de l'année", "Meilleur jour de l'année"],
  ["Mauvaise habitude", "Bonne habitude"],
  ["Personne chat", "Personne chien"],
  ["Sage", "Intelligent"],
  ["Difficile à faire", "Facile à faire"],
  ["Activité mentale", "Activité physique"],
  ["Sujet unanime", "Sujet controversé"],
  ["Plaisir coupable", "Amour assumée"],
  ["Sans talent", "Talentueux"],
  ["Difficile à trouver", "Facile à trouver"],
  ["Homme hideux", "Bel homme"],
  ["Difficile à se rappeler", "Facile à se rappeler"],
  ["Inculte", "Cultivé"],
  ["En bonne santé", "En mauvaise santé"],
  ["Homme mauvais", "Homme bon"],
  ["Historiquement important", "Historiquement insignifiant"],
  ["Sans cheveux", "Chevelu"],
  ["Inflexible", "Flexible"],
  ["Animal domestique normal", "Animal domestique exotique"],
  ["Introverti", "Extraverti"],
  ["Le livre était mieux", "Le film était mieux"],
  ["Mauvais film", "Bon film"],
  ["Moche", "Beau"],
  ["Personne mature", "Personne immature"],
  ["Mieux vaut ne pas l'avoir", "Mieux vaut l'avoir"],
  ["Ordinaire", "Extraordinaire"],
  ["Difficile à prononcer", "Facile à prononcer"],
  ["Mal fait", "Bien fait"],
  ["Pas un sandwich", "Un sandwich"],
  ["Dangereux", "Sans risque"],
  ["Culturellement significatif", "Culturellement insignifiant"],
  ["Optionnel", "Obligatoire"],
  ["Lettre de l'alphabet peu utilisée", "Lettre de l'alphabet très utilisée"],
  ["Mauvaise qualité", "Bonne qualité"],
  ["Animal pas mignon", "Animal mignon"],
  ["Endroit calme", "Endroit bruyant"],
  ["Comédie", "Drame"],
  ["Besoin", "Envie"],
  ["Aliment sec", "Aliment humide"],
  ["Remplaçable", "Irremplaçable"],
  ["Pire athlète de tous les temps", "Meilleur athlète de tous les temps"],
  ["Pas éthique", "Éthique"],
  ["Loisir ennuyeux", "Loisir intéressant"],
  ["Mauvaise garniture de pizza", "Bonne garniture de pizza"],
  ["Dystopie", "Utopie"],
  ["Rugueux", "Lisse"],
  ["Mauvais pour vous", "Bien pour vous"],
  ["Pacifique", "Belliqueux"],
  ["Mauvais film", "Bon film"],
  ["A mauvais goût", "A bon goût"],
  ["Sport", "Jeu"],
  ["Film triste", "Film joyeux"],
  ["Perte de temps", "Il fallait le faire"],
  ["Entreprise la moins démoniaque", "Entreprise la plus démoniaque"],
  ["Casse-dalle", "Repas"],
  ["Incroyable", "Croyable"],
  ["Vulgaire", "Classe"],
  ["Sent mauvais", "Sent bon"],
  ["Star Wars", "Star Trek"],
  ["Animal effrayant", "Animal gentil"],
  ["Culture de masse", "Culture de niche"],
  ["Sombre", "Clair"],
  ["Mauvais acteur", "Bon acteur"],
  ["Difficile à utiliser", "Facile à utiliser"],
  ["Pneumatique", "Filaire"],
  ["Années 1980", "Années 1990"],
  ["Mauvaise personne", "Bonne personne"],
  ["Simple restauration", "Haute gastronomie"],
  ["Doux", "Dur"],
  ["Chose normal à avoir", "Chose bizarre à avoir"],
  ["Droit", "Courbe"],
  ["Exemple à suivre", "Mauvaise influence"],
  ["Majordome inutile", "Majordome utile"],
  ["Personne lambda", "Personne sympathique"],
  ["Film d'action", "Film d'aventure"],
];

const AdvancedSpectrumCards: [string, string][] = [
  ["Court", "Long"],
  ["Pire année de l'histoire", "Meilleure année de l'histoire"],
  ["Célèbre", "Inconnu"],
  ["Dieu le moins fort", "Dieu le plus fort"],
  ["Couleur pas attirante", "Couleur attirante"],
  ["Profitable pour vous", "Profitable pour tout le monde"],
  ["Mauvais président", "Bon président"],
  ["Bizarre", "Étrange"],
  ["Dérivé", "Original"],
  ["Règles", "Mœurs"],
  ["Pire", "Meilleur"],
  ["Petit nombre", "Grand nombre"],
  ["Pas assez", "Trop"],
  ["Difficile de s'asseoir dessus", "Facile de s'asseoir dessus"],
  ["Talent", "Compétence"],
  ["Pire destination de voyage temporel", "Meilleure destination de voyage temporel"],
  ["Pas embrassable", "Embrassable"],
  ["Hétérogène", "Homogène"],
  ["Hors de contrôle", "Sous contrôle"],
  ["Populaire", "Élitiste"],
  ["Non-partisant", "Partisant"],
  ["Nom de chien", "Nom de chat"],
  ["Info peu connue", "Info bien connue"],
  ["Socialiste", "Capitaliste"],
  ["Mauvais bonbon", "Bon bonbon"],
  ["Traditionnel", "Radical"],
  ["Désagréable en bouche", "Agréable en bouche"],
  ["Illégal", "Légal"],
  ["Jamais à l'heure", "Toujours à l'heure"],
  ["Ne sera pas centenaire", "Sera centenaire"],
  ["Personnage de Disney méchant", "Personnage de Disney gentil"],
  ["Similaire", "Identique"],
  ["Mou", "Ferme"],
  ["Sujet marrant", "Sujet sérieux"],
  ["Non parfumé", "Parfumé"],
  ["Horizontal", "Vertical"],
  ["Petit", "Minuscule"],
  ["Mot horrible", "Mot magnifique"],
  ["Tic", "Tac"],
  ["Mauvais conseil", "Bon conseil"],
  ["Illégal", "Interdit"],
  ["Pas de l'art", "Art"],
  ["Potin", "Nouvelle"],
  ["Plaisir coupable (ce qu'on aime sans assumer)", "Purement mauvais"],
  ["Vintage", "Avant-garde"],
  ["Vrai", "Faux"],
  ["Salutation normal", "Salutation bizarre"],
  ["Dictature", "Démocratie"],
  ["Impuissant", "Puissant"],
  ["Vapote", "Ne vapote pas"],
  ["Personne ennuyeuse", "Personne cool"],
  ["Livre médiocre", "Livre de qualité"],
  ["Pensée profonde", "Pensée superficielle"],
  ["Mauvaise école", "Bonne école"],
  ["Sagesse populaire", "Croyance marginale"],
  ["Pire corvée", "Meilleure tâche"],
  ["Espèce en voie d'extinction", "Espèce invasive"],
  ["Bleu", "Vert"],
  ["Fruit", "Légume"],
  ["Science", "Pseudoscience"],
  ["Bavardage", "Sujet de fond"],
  ["Mauvais investissement", "Bon investissement"],
  ["Stationnaire", "Mobile"],
  ["Problème local", "Problème global"],
  ["Captivant", "Terrifiant"],
  ["Nerd", "Mec"],
  ["Attendu", "Inattendu"],
  ["Personne que vous pourriez tabasser", "Personne qui vous tabasserait"],
  ["Limité", "Infini"],
  ["Événement anodin", "Événement solennel"],
  ["Phobie injustifiable", "Phobie justifiable"],
  ["Jeu médiocre", "Jeu de qualité"],
  ["Religieux", "Sacré"],
  ["Léger", "Épicé"],
  ["Vraie personne", "Imposteur"],
  ["Pas naturel", "Naturel"],
  ["Secret", "De notoriété publique"],
  ["Trop petit", "Trop gros"],
  ["Art", "Commerce"],
  ["N'a fait qu'un tube", "Icône de la pop"],
  ["Pokémon pas attirant", "Pokémon attirant"],
  ["Calme", "Bruyant"],
  ["Inclusif", "Exclusif"],
  ["Mauvaise race de chien", "Bonne race de chien"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
