const SpectrumCards: [string, string][] = [
  ["Mau ator", "Bom ator"],
  ["Básico", "Hipster"],
  ["Sem valor", "Valor inestimável"],
  ["Inato", "Adquirido"],
  ["Acontece aos poucos", "Acontece repentinamente"],
  ["Bico", "Carreira"],
  ["Arredondado", "Pontudo"],
  ["Prova que Deus existe", "Prova que Deus não existe"],
  ["Amado", "Odiado"],
  ["Lado luminoso da força", "Lado negro da força"],
  ["Estúpido", "Brilhante"],
  ["Artesanal", "Industrializado"],
  ["Ninguém faz", "Todo mundo faz"],
  ["Vida curta", "Vida longa"],
  ["Trabalho perigoso", "Trabalho seguro"],
  ["Fantasia", "Ficção científica"],
  ["Simples", "Requintado"],
  ["Tem uma má reputação", "Tem uma boa reputação"],
  ["Ético para comer", "Não ético para comer"],
  ["Filme pipoca", "Filme cabeça"],
  ["Cafona", "Na moda"],
  ["Guerreiro da liberdade", "Terrorista"],
  ["Bom superpoder", "Mau superpoder"],
  ["Não efetivo", "Efetivo"],
  ["Melhor quente", "Melhor frio"],
  ["Quadrado", "Redondo"],
  ["Temporário", "Permanente"],
  ["Parece com uma pessoa", "Não parece com uma pessoa"],
  ["Chato", "Legal"],
  ["Pior ser humano vivo", "Melhor ser humano vivo"],
  ["Subestimado", "Superestimado"],
  ["Comida que faz sujeira", "Comida que não suja"],
  ["Imperdoável", "Perdoável"],
  ["Falha", "Obra prima"],
  ["Inofensivo", "Prejudicial"],
  ["Grifinória", "Sonserina"],
  ["Não higiênico", "Higiênico"],
  ["Música ruim", "Música boa"],
  ["Inútil", "Útil"],
  ["Filme que melhoraria com o Godzilla", "Filme que pioraria com o Godzilla"],
  ["Sem importância", "Importante"],
  ["Fácil de soletrar", "Difícil de soletrar"],
  ["Vício", "Virtude"],
  ["Músico subestimado", "Músico superestimado"],
  ["Atividade impopular", "Atividade popular"],
  ["Dividido", "Inteiro"],
  ["Não confiável", "Confiável"],
  ["Fácil de matar", "Difícil de matar"],
  ["Instável", "Estável"],
  ["Animal arredondado", "Animal pontudo"],
  ["Programa de TV ruim", "Programa de TV bom"],
  ["Tradicionalmente masculino", "Tradicionalmente feminino"],
  ["Parte inútil do corpo", "Parte útil do corpo"],
  ["Moda passageira", "Clássico"],
  ["Fraco", "Forte"],
  ["Cereal horrível", "Cereal delicioso"],
  ["Ruim", "Bom"],
  ["Levemente viciante", "Altamente viciante"],
  ["Inútil em uma emergência", "Útil em uma emergência"],
  ["Para crianças", "Para adultos"],
  ["Vilão", "Herói"],
  ["Coisa subestimada de se fazer", "Coisa superestimada de se fazer"],
  ["Entediante", "Empolgante"],
  ["Cheiroso no mal sentido", "Cheiroso no bom sentido"],
  ["Impopular", "Popular"],
  ["Amigo", "Inimigo"],
  ["Invenção útil", "Invenção inútil"],
  ["Liberal", "Conservador"],
  ["Quente", "Frio"],
  ["Normal", "Estranho"],
  ["Sem cor", "Colorido"],
  ["Pouco calórico", "Muito calórico"],
  ["Assunto fácil", "Assunto difícil"],
  ["Desconhecido", "Famoso"],
  ["Raro", "Comum"],
  ["Emoji sem graça", "Emoji descolado"],
  ["Barato", "Caro"],
  ["Arma subestimada", "Arma superestimada"],
  ["Parece ruim", "Parece bom"],
  ["Não essencial", "Essencial"],
  ["Sujo", "Limpo"],
  ["Requer sorte", "Requer habilidade"],
  ["Sem gosto", "Saboroso"],
  ["Tópico sem graça", "Tópico fascinante"],
  ["Casual", "Formal"],
  ["Mal pago", "Pago exageradamente"],
  ["Seco", "Molhado"],
  ["Habilidade subestimada", "Habilidade superestimada"],
  ["Proibido", "Incentivado"],
  ["Música triste", "Música feliz"],
  ["Frágil", "Durável"],
  ["Nerd", "Bobo"],
  ["Bem", "Mal"],
  ["Pior dia do ano", "Melhor dia do ano"],
  ["Mau hábito", "Hábito bom"],
  ["Pessoa que prefere gatos", "Pessoa que prefere cachorros"],
  ["Sábio", "Inteligente"],
  ["Difícil de fazer", "Fácil de fazer"],
  ["Atividade mental", "Atividade física"],
  ["Assunto sem controversa", "Assunto controverso"],
  ["Gosto vergonhoso", "Orgulho de dizer em público que gosta"],
  ["Sem talento", "Talentoso"],
  ["Difícil de achar", "Fácil de achar"],
  ["Homem feio", "Homem bonito"],
  ["Difícil de lembrar", "Fácil de lembrar"],
  ["Tosco", "Refinado"],
  ["Prejudicial", "Saudável"],
  ["Homem mau", "Homem bom"],
  ["Historicamente importante", "Historicamente irrelevante"],
  ["Sem cabelo", "Cabeludo"],
  ["Inflexível", "Flexível"],
  ["Bicho de estimação normal", "Bicho de estimação exótico"],
  ["Introvertido", "Extrovertido"],
  ["O livro é melhor", "O filme é melhor"],
  ["Filme ruim", "Filme bom"],
  ["Feio", "Lindo"],
  ["Pessoa madura", "Pessoa imatura"],
  ["Coisa subestimada de se ter", "Coisa superestimada de se ter"],
  ["Ordinário", "Extraordinário"],
  ["Difícil de pronunciar", "Fácil de pronunciar"],
  ["Mal feito", "Bem feito"],
  ["Não é um sanduíche", "É um sanduíche"],
  ["Perigoso", "Seguro"],
  ["Culturalmente significante", "Culturalmente insignificante"],
  ["Opcional", "Obrigatório"],
  ["Letra subestimada do alfabeto", "Letra superestimada do alfabeto"],
  ["Baixa qualidade", "Alta qualidade"],
  ["Animal sem graça", "Animal legal"],
  ["Lugar silencioso", "Lugar barulhento"],
  ["Comédia", "Drama"],
  ["Necessidade", "Desejo"],
  ["Comida seca", "Comida molhada"],
  ["Substituível", "Insubstituível"],
  ["Pior atleta de todos os tempos", "Melhor atleta de todos os tempos"],
  ["Não ético", "Ético"],
  ["Hobby entediante", "Hobby interessante"],
  ["Sabor de pizza ruim", "Sabor de pizza bom"],
  ["Distopia", "Utopia"],
  ["Áspero", "Liso"],
  ["Faz mal para você", "Faz bem para você"],
  ["Pacífico", "Bélico"],
  ["Filme subestimado", "Filme superestimado"],
  ["Tem gosto ruim", "Tem gosto bom"],
  ["Esporte", "Jogo"],
  ["Filme triste", "Filme feliz"],
  ["Desperdício de tempo", "Bom uso do tempo"],
  ["Empresa menos malvada", "Empresa mais malvada"],
  ["Petisco", "Refeição"],
  ["Inacreditável", "Crível"],
  ["Chinfrim", "Elegante"],
  ["Cheira mal", "Cheira bem"],
  ["Star Wars", "Star Trek"],
  ["Animal assustador", "Animal fofo"],
  ["Massa", "Nicho"],
  ["Escuridão", "Luz"],
  ["Ator subestimado", "Ator superestimado"],
  ["Difícil de usar", "Fácil de usar"],
  ["Cansado", "Ligado no 220"],
  ["Anos 80", "Anos 90"],
  ["Má pessoa", "Boa pessoa"],
  ["Comida para sustento", "Alta gastronomia"],
  ["Mole", "Duro"],
  ["Coisa normal de se ter", "Coisa estranha de se ter"],
  ["Reto", "Curvo"],
  ["Modelo a ser seguido", "Má influência"],
  ["Graduação inútil", "Graduação útil"],
  ["Pessoa malvada", "Pessoa gentil"],
  ["Filme de ação", "Filme de aventura"],
];

const AdvancedSpectrumCards: [string, string][] = [
  ["Curto", "Longo"],
  ["Pior ano na história", "Melhor ano na história"],
  ["Famoso", "Infâme"],
  ["Deus menos poderoso", "Deus mais poderoso"],
  ["Cor sem graça", "Cor bacana"],
  ["Beneficia você", "Beneficia a todos"],
  ["Mau presidente", "Bom presidente"],
  ["Bizarro", "Estranho"],
  ["Inspirado", "Original"],
  ["Etiqueta", "Boas maneiras"],
  ["O pior", "O melhor"],
  ["Número pequeno", "Número grande"],
  ["Não é o suficiente", "É demais"],
  ["Difícil de sentar em cima", "Fácil de sentar em cima"],
  ["Talento", "Habilidade"],
  ["Pior era para viajar no tempo", "Melhor era para viajar no tempo"],
  ["Não abracável", "Abracável"],
  ["Heterogeneo", "Homogeneo"],
  ["Fora de controle", "Controlado"],
  ["Popular", "Elitista"],
  ["Não partidário", "Partidário"],
  ["Nome de cachorro", "Nome de gato"],
  ["Fato pouco conhecido", "Fato amplamente conhecido"],
  ["Socialista", "Capitalista"],
  ["Doce ruim", "Doce bom"],
  ["Tradicional", "Radical"],
  ["Sensação ruim na boca", "Sensação boa na boca"],
  ["Ilegal", "Legal"],
  ["Sempre em atraso", "Sempre pontual"],
  ["Não vai viver até os 100 anos", "Vai viver até os 100 anos"],
  ["Personagem da Disney ruim", "Personagem da Disney bom"],
  ["Similar", "Idêntico"],
  ["Flácido", "Firme"],
  ["Assunto engraçado", "Assunto sério"],
  ["Sem perfume", "Perfumado"],
  ["Horizontal", "Vertical"],
  ["Pequeno", "Minúsculo"],
  ["Palavra feia", "Palavra bonita"],
  ["Tick", "Tock"],
  ["Mau conselho", "Bom conselho"],
  ["Ilegal", "Proibido"],
  ["Não arte", "Arte"],
  ["Fofoca", "Notícia"],
  ["Gosto vergonhoso", "Apenas ruim mesmo"],
  ["Moda antiga", "A frente de seu tempo"],
  ["Verdadeiro", "Falso"],
  ["Cumprimento normal", "Cumprimento esquisito"],
  ["Ditadura", "Democracia"],
  ["Sem poder", "Poderoso"],
  ["Usa cigarro eletrônico", "Não usa cigarro eletrônico"],
  ["Pessoa chata", "Pessoa divertida"],
  ["Livro subestimado", "Livro superestimado"],
  ["Pensamento profundo", "Pensamento raso"],
  ["Má escola", "Boa escola"],
  ["Sabedoria popular", "Crença marginal"],
  ["Pior tarefa doméstica", "Melhor tarefa doméstica"],
  ["Espécie ameaçada de extinção", "Espécie superpopulada"],
  ["Azul", "Verde"],
  ["Fruta", "Vegetal"],
  ["Ciência", "Pseudociência"],
  ["Papo furado", "Conversa pesada"],
  ["Mal investimento", "Bom investimento"],
  ["Estacionário", "Móvel"],
  ["Problema local", "Problema global"],
  ["Emocionante", "Aterrorizante"],
  ["Nerd", "Esportista"],
  ["Esperado", "Inesperado"],
  ["Pessoa que você poderia bater", "Pessoa que você apanharia"],
  ["Limitado", "Infinito"],
  ["Evento casual", "Evento formal"],
  ["Fobia irracional", "Fobia racional"],
  ["Jogo subestimado", "Jogo superestimado"],
  ["Religioso", "Sacrílego"],
  ["Suave", "Apimentado"],
  ["Pessoa genuína", "Pessoa dissimulada"],
  ["Não natural", "Natural"],
  ["Segredo", "Conhecimento público"],
  ["Muito pequeno", "Muito grande"],
  ["Arte", "Comércio"],
  ["Estrela de um só hit", "Ícone do pop"],
  ["Pokémon sem graça", "Pokémon legal"],
  ["Silencioso", "Barulhento"],
  ["Inclusivo", "Exclusivo"],
  ["Raça de cachorro ruim", "Raça de cachorro boa"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
